### ISSUE TITLE
Allow visitors to stop playback of pre-recorded sounds

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-cochlear-implant#21]
After a visitor starts a sound, could you turn the "play" icon into a "stop" icon?
If a visitor touches the card-button in this state, it would stop playback and swap back to the "play" icon. 
(Sorry, we hadn't thought of this earlier. Let me know if this is overly difficult.)

**Comment by abdulrauf11** [comment]
Hey @tnordberg, should it stop or pause the audio when clicked?

Also, can the design link be updated with the "stop" button as well?

**Comment by tnordberg** [comment]
Hey @abdulrauf11 the sound should stop and reset playback.

Yes, I think we can add the "stop" icon in Figma today or early tomorrow.

**Comment by tnordberg** [comment]
A stop button example has been added to the Figma design:
![image (9)](https://user-images.githubusercontent.com/8516314/116135562-e4458a80-a696-11eb-80ec-54033f09c156.png)
