### ISSUE TITLE
Update image/sound credits so both can fit

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-cochlear-implant#22]
Please change the "Sound credit" font to be small enough to fit both an image and sound credit under each, as seen in this mockup: https://d.pr/i/FG44Sa

Please use the following credits:

Bird
```
Image: Andreas Trepte, www.avi-fauna.info
Sound: Courtesy Daniel71953
```

Traffic
```
Image: ⓒiStock.com / life in shots
Sound: Zapsplat, https://www.zapsplat.com
```

Flag
```
Image: ⓒiStock.com / creisinger
Sound: Daniel71953 / Creative Commons
```

**Comment by abdulrauf11** [comment]
@tnordberg Will the credits be the same for English and Arabic?

**Comment by tnordberg** [comment]
@abdulrauf11 thank you for flagging this. These credits should also be translated, so please pull the credits from your language files. 

Please use the Arabic in this txt file:
[CochlearArabicCredits.txt](https://github.com/scimusmn/tsck-cochlear-implant/files/6395166/CochlearArabicCredits.txt)

**Comment by tnordberg** [comment]
Hi @abdulrauf11 apologies for reversing, but I found out this morning these credits actually can be English-only.

If you’ve already added the Arabic, that’s great. If not, don’t bother adding the Arabic.
