### ISSUE TITLE
Redesign Secondary Info Modal

### ISSUE THREAD

**Issue by abdulrauf11** [scimusmn/tsck-cochlear-implant#27]
Can the modal be redesigned with proper content and image?

If that's not possible, can we get just get the two images instead? Currently, we're cropping them from the bigger image being used in the modal.

**Comment by tnordberg** [comment]
Hey @abdulrauf11 the images you cropped look good to us, but I will check on this. Depending how busy our designer is, it may be simplest for us to just provide the cropped images.

**Comment by tnordberg** [comment]
@abdulrauf11 our designer is unable to redesign that screen right now, but they cropped an image to the correct size for you.

We don't have final Arabic translations, but please use these as placeholders, then I can drop in the final Arabic image later.

[info-diagram-images.zip](https://github.com/scimusmn/tsck-cochlear-implant/files/6379717/info-diagram-images.zip)
