### ISSUE TITLE
Occasionally Gatsby Images fail to load

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-cochlear-implant#36]
The Gatsby Images sporadically disappear, or fail to load. 

https://d.pr/v/idlXwg

It seems to happen either after an inactivity refresh, or the first time the application loads. Reloading the page seems to fix it, but this happened 3–4 times while we were testing. 

@abdulrauf11 do you have any ideas on what might be causing this? I haven't seen anything suspicious come out in the console.

**Comment by abdulrauf11** [comment]
Hey @tnordberg, I haven't been able to reproduce this issue on my end. Can you share any more details on this? Perhaps the device it was tested on?

**Comment by abdulrauf11** [comment]
Worst case scenario, we can remove the gatsby image and use plain <img /> tags. Before using them, I'll have to manually optimize them though. However, it'll be easier since we only need to optimize them for one screen size.

**Comment by tnordberg** [comment]
Yeah, I haven't been able to reproduce it on your preview link either. It only happens when running fullscreen on the exhibit computer.

Could you go ahead and replace the Gatsby Images with <img>s optimized for the 1920x1080 display?

**Comment by abdulrauf11** [comment]
@tnordberg Yes, that would be a better option.
