### ISSUE TITLE
Ability to interrupt playback/recordings

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-cochlear-implant#37]
Please update to accommodate these two scenarios:

- While a **pre-recorded** sound is playing, user should be able to tap the ‘record’ button. This would immediately stop current playback and start a new recording.
- While playing back a **recorded** sound, user should be able to tap a pre-recorded sound button. This would immediately cancel the recording to start playing the pre-recorded sound.

**Comment by abdulrauf11** [comment]
@tnordberg To clarify the second point, while the user is recording/playing their voice they can tap and play any of the three pre-recorded sounds. 

If they do that, their recording will be cancelled and the component will return to the pre-recording state showing only the large microphone button. Is that correct?

**Comment by tnordberg** [comment]
@abdulrauf11 that's correct. It can delete the in-progress recording.

**Comment by abdulrauf11** [comment]
@tnordberg Should it delete the recording if it's not in-progress? (in the case where the user is not recording or playing their recorded sound)

<img width="731" alt="Screenshot 2021-05-18 at 7 22 49 PM" src="https://user-images.githubusercontent.com/26784406/118668581-7102e480-b80e-11eb-995e-7f1d9e39f93a.png">

**Comment by tnordberg** [comment]
@abdulrauf11 no, thanks for asking.

If the user records to completion, then plays a pre-recorded sound, their recording should remain.

**Comment by abdulrauf11** [comment]
@tnordberg So far I've understood these 3 cases:

1. While recording is **in-progress**, and the user plays a pre-recorded sound: the recording will be deleted.
2. If the recording is **complete**, and the user plays a pre-recorded sound:  the recording will not be affected.
3. While the recording is **playing**, and the user plays a pre-recorded sound: the recording will be deleted.

Is that correct?

**Comment by tnordberg** [comment]
@abdulrauf11 Almost. Thanks for clarifying.

1. Correct
2. Correct
3. Playback of recording should stop, but not be deleted.
